export declare const TRUE = true;
export declare const FALSE = false;
export declare const NULL: any;
export declare const UNDEFINED: any;
export declare const RAW_DATE = "date";
export declare const RAW_ARRAY = "array";
export declare const RAW_STRING = "string";
export declare const RAW_BOOLEAN = "boolean";
export declare const RAW_NUMERIC = "numeric";
export declare const RAW_NUMBER = "number";
export declare const RAW_OBJECT = "object";
export declare const RAW_FUNCTION = "function";
export declare const RAW_HORIZONTAL = "horizontal";
export declare const RAW_VERTICAL = "vertical";
export declare const RAW_INLINE = "inline";
export declare const RAW_TINY = "tiny";
export declare const RAW_SMALL = "small";
export declare const RAW_DEFAULT = "default";
export declare const RAW_LARGE = "large";
export declare const RAW_HUGE = "huge";
export declare const RAW_ALWAYS = "always";
export declare const RAW_NEVER = "never";
export declare const RAW_HOVER = "hover";
export declare const RAW_CLICK = "click";
export declare const RAW_CUSTOM = "custom";
export declare const RAW_CENTER = "center";
export declare const RAW_MIDDLE = "middle";
export declare const RAW_TOP = "top";
export declare const RAW_TOP_START = "top-start";
export declare const RAW_TOP_END = "top-end";
export declare const RAW_BOTTOM = "bottom";
export declare const RAW_BOTTOM_START = "bottom-start";
export declare const RAW_BOTTOM_END = "bottom-end";
export declare const RAW_LEFT = "left";
export declare const RAW_LEFT_START = "left-start";
export declare const RAW_LEFT_END = "left-end";
export declare const RAW_RIGHT = "right";
export declare const RAW_RIGHT_START = "right-start";
export declare const RAW_RIGHT_END = "right-end";
export declare const RAW_TYPE_PRIMARY = "primary";
export declare const RAW_TYPE_SUCCESS = "success";
export declare const RAW_TYPE_WARNING = "warning";
export declare const RAW_TYPE_ERROR = "error";
export declare const RAW_TYPE_INFO = "info";
export declare const RAW_TYPE_DASHED = "dashed";
export declare const RAW_TYPE_LINK = "link";
export declare const RAW_TYPE_TITLE = "title";
export declare const RAW_TYPE_CONTENT = "content";
export declare const RAW_TYPE_MUTED = "muted";
export declare const RAW_SHAPE_CIRCLE = "circle";
export declare const RAW_SHAPE_ROUND = "round";
export declare const RAW_EVENT_KEYPRESS = "keypress";
export declare const RAW_EVENT_KEYDOWN = "keydown";
export declare const RAW_EVENT_KEYUP = "keyup";
export declare const RAW_EVENT_SCROLL = "scroll";
export declare const RAW_EVENT_RESIZE = "resize";
export declare const RAW_EVENT_BEFORE_DESTROY = "beforeDestroy.hook";
export declare const RAW_DARK = "dark";
export declare const RAW_LIGHT = "light";
export declare const RAW_THEME_ARRAY: string[];
export declare const RAW_STATUS_ARRAY: string[];
export declare const RAW_TYPE_ARRAY: string[];
export declare const RAW_SIZE_ARRAY: string[];
export declare const RAW_SIZE_COMMON: string[];
export declare const RAW_PLACEMENT_ARRAY: string[];
export declare const WINDOW: Window & typeof globalThis;
export declare const DOCUMENT: Document;
export declare const BODY: HTMLElement;
export declare const HOVER_DELAY = 100;
