export declare const screenWidth: number;
export declare const isMac: boolean;
export declare const supportTransform: boolean;
export declare const supportFlexGap: boolean;
export declare function onTransitionEnd(el: HTMLElement, callback: () => void): void;
export declare function getPageX(): number;
export declare function getPageY(): number;
export declare const requestAnimationFrame: any;
export declare function contains(element: HTMLElement, target: HTMLElement): boolean;
export declare function toNumber(value: any, defaultValue?: any): any;
export declare function toString(value: any, defaultValue?: any): string;
export declare function toBoolean(value: any): any;
export declare function toPixel(value: number): string;
export declare function toPercent(value: number): string;
export declare function findComponentUpward(parent: any, componentName: string | string[]): any;
export declare function oneOf(values: any[]): (key: string, value: any, componentName: string) => void;
export declare function getNowTime(): number;
export declare function formatMillisecond(value: number, options: {
    format: string;
    trimDay?: boolean;
    trimHour?: boolean;
}): string;
export declare function padStart(value: number, length?: number): string;
export declare function scrollTo(element: HTMLElement | Window, from: number, to: number, duration?: number, callback?: () => void): void;
export declare function spaceListStyle(gaps: number[] | void, vertical: boolean, autoWrap: boolean, style?: any): object[] | void;
export declare function spaceItemStyle(gaps: number[] | void, vertical: boolean, autoWrap: boolean, style?: Record<string, string>): Record<string, string> | void;
